[package]
name = "rust_makepng"
version = "0.1.0"
authors = ["gregstoll <greg@gregstoll.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.16.8"
serde_json = "1.0"
anyhow = "1.0"